version: '3'
services:
  myservice:
    image: c5f18ec0d33b
    container_name: 8c277d87242a
    volumes:
      - /root/55-seconds:/root/55-seconds
    command: bash -c "cd /root/55-seconds && ./start.sh"


version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Expose the port (adjust as needed)
    volumes:
      - .:/app      # Bind mount the project directory
    environment:
      - NODE_ENV=production
